name: Diabetes Health Indicators Workflow
on:
  push:
    branches:
      - main
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - run: echo "⚙ Install code dependencies ..."

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

  preprocess:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: echo " 🎬 Preprocess data ..."
      - name: List files in src directory
        run: ls -la
      - name: Run preprocess function
        run: python -m src.preprocess

  tests:
    needs: preprocess
    runs-on: ubuntu-latest
    steps:
      - run: echo "📌 Run tests ..."
      - name: Run tests
        run: pytest