name: Diabetes Health Indicators Workflow
on:
  push:
    branches:
      - main
jobs:
  preprocess:
    runs-on: ubuntu-latest
    env:
      AWS_LAMBDA_ROLE_ARN: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: echo "⚙ Install code dependencies ..."
      - name: Install dependencies
        run: pip install -r requirements.txt

      - run: echo " 🎬 Run preprocess function ..."
      - name: Run preprocess function
        run: python -m src.preprocess

  tests:
    needs: preprocess
    runs-on: ubuntu-latest
    steps:
      - run: echo "📌 Run tests ..."
      - name: Run tests
        run: pytest